PECE-project/drupal-pece

- src/docs/source/docs/installation.md
While here, remove stray '\' characters.
> Fix #47, improve wording of question about updates.

- web/profiles/pece/pece.info.yml
- web/sites/default/settings.php
Change default theme to adminimal theme and fixing error in settings.php in line 808
> PECE-2.190806.4 change default theme to adminimal theme and fixing error in settings.php in line 808

- config/sync/field.field.node.pece_group.field_pece_media_image.yml
update thumbnail fields to required
> update thumbnail field of the content type group to be required

- config/sync/core.entity_form_display.node.pece_group.default.yml
- config/sync/core.entity_form_display.node.pece_project.default.yml
- config/sync/core.entity_view_display.node.pece_group.default.yml
- config/sync/core.entity_view_display.node.pece_project.default.yml
- config/sync/core.entity_view_display.node.pece_project.teaser.yml
- config/sync/core.extension.yml
- config/sync/language.entity.en.yml
- config/sync/language.entity.und.yml
- config/sync/language.entity.zxx.yml
- config/sync/language.mappings.yml
- config/sync/language.negotiation.yml
- config/sync/language.types.yml
- config/sync/locale.settings.yml
alguns dos arquivos que vieram depois de dar o comando git merge mostraram alteração no git status, favor conferir.
> Pece 2.190801.4  multilingual support enabled

- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/metatag.metatag_defaults.403.yml
- config/sync/metatag.metatag_defaults.404.yml
- config/sync/metatag.metatag_defaults.front.yml
- config/sync/metatag.metatag_defaults.global.yml
- config/sync/metatag.metatag_defaults.node.yml
- config/sync/metatag.metatag_defaults.taxonomy_term.yml
- config/sync/metatag.metatag_defaults.user.yml
- web/profiles/pece/pece.info.yml
> 190801.6metatag

- docker-compose.yml
correção do erro que estava dando no traefild
> traefik error correction

- config/sync/language.content_settings.node.pece_project.yml
enable multilingual support task fix
> Pece 2.190801.4.1 enable multilingual support task fix

- src/docs/source/docs/index.md
@lindsaypoirier -- Can you regenerate the docs after this gets committed?
> Change Slack link in docs to invite link so new users can sign up.

- config/sync/search_api.settings.yml
activation of the search api module and placing as dependency
> Pece 2.190801.5 activation of the search api module and placing as dependency

- src/front/.eslintrc.js
- src/front/nuxt.config.js
- src/front/package-lock.json
- src/front/package.json
- src/front/plugins/a11y/vue-announcer.js
- src/front/plugins/a11y/vue-axe.js
- src/front/plugins/a11y/vue-skip-to.js
- vue-axe
- vue-announcer
- vue-skip-to
- vue-a11y-utils
- eslint-plugin-vue-a11y
...
> Add plugins and settings for code accessibility

- composer.json
- composer.lock
- config/sync/core.extension.yml
- web/profiles/pece/module/nyx_graphql/modules/graphql_people/src/Plugin/GraphQL/DataProducer/CreateUser.php
Add exception in the graphql api and update drupal core
> Pece 2.0402.1 people api

- README.md
> Small typo fix (Contribution -> Contributions) to test Slack hook.

- src/modules/pece/pece_essay/plugins/ctools/content_types/view_essay_link.inc
- src/modules/pece/pece_timeline_essay/plugins/ctools/content_types/view_timeline_essay_link.inc
In today's meeting we got a request to change the text of the Return to Metadata buttons.
> Edited text on Essay Pages

- docker-compose-prod.yml
- docker-compose.yml
Wait to approve in the dev branch
> WIP: Change name service for dockers to use in the migrate.

- README.md
This is my new readme suggestion for run the pece 2.0 in "localhost".
> new readme suggestion

- config/sync/blocktabs.blocktabs.pece_home_recent_content.yml
blocktabs.blocktabs.pece_home_recent_content.yml
> inserting blocktabs in config/sync

- config/sync/core.entity_view_display.node.pece_artifact_image.default.yml
- config/sync/field.storage.node.field_contributed_date.yml
Create the contributed date field.
Change the artifact image structure.
> Update the artifact image structure

- config/sync/core.entity_view_display.node.pece_artifact_audio.default.yml
- config/sync/core.entity_view_display.node.pece_artifact_audio.teaser.yml
Add the contributed date field.
Update Audio artifact page structure.
> Pece 2.230124.2

- config/sync/core.entity_view_display.node.artifact_video.default.yml
- config/sync/core.entity_view_display.node.artifact_video.teaser.yml
- config/sync/field.field.node.artifact_video.field_contributed_date.yml
Add the contributed date field.
Update the artifact video structure.
> Pece 2.230124.3

- codeception.yml
- composer.json
- composer.lock
- tests/_output/.gitignore
- tests/_support/AcceptanceTester.php
- tests/_support/FunctionalTester.php
- tests/_support/Helper/Acceptance.php
- tests/_support/Helper/Functional.php
- tests/_support/Helper/Unit.php
- tests/_support/UnitTester.php
- tests/_support/_generated/.gitignore
- tests/acceptance.suite.yml
- tests/acceptance/FirstCest.php
- tests/functional.suite.yml
- tests/unit.suite.yml
make shell
composer require codeception/module-phpbrowser --dev
composer require codeception/codeception --dev
composer require codeception/module-asserts --dev
php vendor/bin/codecept bootstrap
php vendor/bin/codecept g:cest acceptance First
php vendor/bin/codecept run --steps
> [PECE-230215.1] Codeception installed and configured.

- .github/workflows/codeql.yml
CodeQL Acrion v1 is deprecated. Updating it to V2 on codeql.yml
> Fix #554 - Update CodeQL Action settings. 
